Default: &defaults
  database: FFTYesod.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: FFTYesod_test.sqlite3
  <<: *defaults

Staging:
  database: FFTYesod_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: FFTYesod_production.sqlite3
  poolsize: 100
  <<: *defaults
